### ISSUE TITLE
(Virtual) Memory explosion

### ISSUE THREAD

**Issue by AltGr** [AltGr/Camelus#1]
After a while, the program seems to fail on the server with "Cannot allocate memory" errors ; I couldn't reproduce locally, but have some results.
- [ocp-memprof](http://memprof.typerex.org/users/464527645bfe7266d83e8f3c716f1090/2015-06-19_07-43-24_0a33a312c50a38f011f8f209cb6e5262_495/index.html) didn't return any unexpected memory usage or leak ; memory peaks at 70MB when we load the git with all opam files in memory, which seems reasonable.
- I traced system memory usage:
  ![p2](https://cloud.githubusercontent.com/assets/807966/8247992/4ad134f0-1694-11e5-8d0b-da0298348d0c.png)
  Resident memory (VmRSS) stays very reasonable, however, virtual memory (VmSize) jumps to above 100GB... I guess that's where we hit a wall. This is using Linux's `/proc/pid/status`.
  @samoht, a clue what's happening ? I am guessing maybe too many mmaps ? Or am I doing something plainly wrong with git or lwt ? The peaks are reached during the [`opam_files` function](https://github.com/AltGr/opam-ci/blob/91e5fa1fc870ae3212046ab4f19b16da3999a585/opam_ci.ml#L148-L179).

**Comment by edwintorok** [comment]
How many system threads do you have when this happens? AFAIK Lwt uses a pool of workers for blocking (i.e. non-socket) IO and the default for that is 1000 system threads that are created on demand, and each thread needs its own stack which is fairly large by default.
I set a smaller value in my own program and that seems to reduce virtual memory usage:
[Lwt_unix.set_pool_size 64](http://gitweb.skylable.com/gitweb/?p=libres3.git;a=blob;f=libres3/src/ocsigen/libres3_ocsigen.ml;h=1acbdea202ffa8302a66329bd4eb1e330b06552b;hb=HEAD#l327)
Alternatively you could try reducing the stack size for the workers using `pthread_attr_setstacksize`

**Comment by AltGr** [comment]
@edwintorok thanks for the pointer. In these case it seems to stay at 2 threads though, which makes sense since only the web server and processing run in parallel (I wanted to keep things simple to begin with, and the processing writes to the git directory).

I've disabled the instability checks for now, as it's better to have just the lint than nothing after the bot has choked.

**Comment by AltGr** [comment]
I tried getting through the Git.Memory backend to see what happened: it fails at [Git_memory.write_pack].

@samoht any hints ? Should I report to ocaml-git ?

**Comment by AltGr** [comment]
(mem otherwise jumps to ~900MB, and virtual just above 1GB, which is what I would have expected)

**Comment by AltGr** [comment]
I suspect the pack handling from ocaml-git; however, trying with `~unpack:true`, I can't find the references anymore (i.e. nothing works)

**Comment by shinzui** [comment]
Is this still an open issue?

**Comment by AltGr** [comment]
Indeed, this has been fixed. I don't remember exactly which it was, but there were both fixes for ocaml-git, and an important fix for dose's installability check.
Now it seems that after a month or so, there are too many threads left alive, but it's not really blocking and would be on lwt's side.
Thanks!
