### ISSUE TITLE
Make camelus's homepage this repo

### ISSUE THREAD

**Issue by dsheets** [AltGr/Camelus#3]
Otherwise it's not obvious that the source of the bot lives here.

**Comment by dsheets** [comment]
This should take 2 seconds.

**Comment by AltGr** [comment]
yes yes, sorry! :)

**Comment by avsm** [comment]
should we just shift to the ocaml repo? camelus is pretty successfully embedded into opam's workflow now, hurrah! :)

**Comment by AltGr** [comment]
Done, and renamed the repo to Camelus, because we don't need to distinguish between the project and the instance all that much.
I don't know exactly how Github redirects work, but it seems safer to not rename and shift owner at the same time.

**Comment by dsheets** [comment]
Changing the repo owner may be a good idea (or not) but this immediate issue is resolved.
